describe('test requests ',function(){
    it('mock and API response',function(){
        cy.server();           // enable response stubbing
        cy.route({
          method: 'POST',      // Route all GET requests
          url: '/api/account/login',    // that have a URL that matches '/users/*'
          response:{"result":{"userHeader":{"balance":126.24,"bettingBalance":126.24,"pendingBets":0,"CrownMembershipLinked":false,"ResidentialPostCode":"3000","Title":"","Surname":"mocksurname","MiddleName":"","FirstName":"mockname"},"html":{"top-menu":"<ul>\n    <li><a class=\"racing-nav \" href=\"\/racing-betting\">\n        <svg role=\"presentation\" class=\"sprite-icon-nav\"><use xlink:href=\"#racing-icon\"><\/use><\/svg>\n        <div>Racing<\/div><\/a>\n    <\/li>\n    <li><a class=\"sports-nav \" href=\"\/sports-betting\">\n        <svg role=\"presentation\" class=\"sprite-icon-nav\"><use xlink:href=\"#sports-icon\"><\/use><\/svg>\n        <div>Sports<\/div><\/a>\n    <\/li>\n        <li>\n    <a class=\"live-betting-nav \" href=\"\/live-in-play-betting\">\n        <svg role=\"presentation\" class=\"sprite-icon-nav\"><use xlink:href=\"#stopwatch\"><\/use><\/svg>\n        <div>Live Betting<\/div>\n    <\/a>\n<\/li>\n\n        <li><a class=\"multi-express-nav \"\n        href=\"\/multi-express\">\n        <svg role=\"presentation\" class=\"sprite-icon-nav\"><use xlink:href=\"#multi-express-icon\"><\/use><\/svg>\n        <div>Multi Express<\/div>\n    <\/a><\/li>\n\n\n\n<li>\n    <a class=\"rewards-nav \"\n       href=\"\/rewards\">\n        <svg role=\"presentation\" class=\"sprite-icon-nav\"><use xlink:href=\"#rewards\"><\/use><\/svg>\n        <div>Rewards<\/div>\n    <\/a>\n<\/li>\n\n<li><a class=\"promotions-nav \"\n    href=\"\/betting-promotions\">\n    <svg role=\"presentation\" class=\"sprite-icon-nav\"><use xlink:href=\"#promotions\"><\/use><\/svg>\n    <div>Promotions<\/div>\n<\/a><\/li>\n\n\n<\/ul>\n"},"customerType":"2","ShowWelcomeBack":false,"JsonTakeABreakOptions":null,"isBoostEligible":false},"success":true},
            });
        cy.route({
          method: 'GET',      // Route all GET requests
          url: '/api/account/detail',    // that have a URL that matches '/users/*'
          response:{"result":[{"ClientID":2964429,"OrgID":1,"AccountNumber":"1243991","PhoneId":"1243991","BPayReference":"29644291","Title":"","Surname":"MOCK SURNAME","MiddleName":"","FirstName":"MOCK USERNAME","Gender":"","DOBDatetime":"1991-08-08T00:00:00Z","DOB":"08\/08\/1991","Username":"Vivekb","PasswordReset":false,"Email":"Vivek.bhardwaj@beteasy.com.au","MobileNo":"0400000000","SignupDate":"2018-11-11T22:49:24.617Z","SignupChannelID":1,"IsCreditClient":false,"ClientProfileID":0,"BetInterceptRuleID":1,"IsTest":true,"IsBookmaker":false,"CreditLimit":0,"LedgerID":0,"CampaignSignedUpID":0,"VerificationID":1,"ResidentialAddressNo":"120","ResidentialAddress1":"COLLINS ST","ResidentialSuburb":"MELBOURNE","ResidentialStateCode":"VIC","ResidentialPostCode":"3000","ResidentialCountryCode":"AUS","ClientHandlerID":0,"IsSelfExcluded":false,"Migration":{"IsMigratedCustomer":false,"HasAcceptedTerms":false,"HasSeenPromo":false},"LiveVision":{"SportVisionAvailable":true,"RacingVisionAvailable":true},"CrownMembershipLinked":false,"CrownMembershipLinkStatus":"0","ClientProfile":{"ClientProfileID":0,"ClientProfile":"Standard","OverridePriceTypeID":0},"Verification":{"VerificationID":1,"Verification":"Verified Manually"},"Accounts":[{"ClientID":0,"AccountTypeID":1,"CurrencyCode":"AUD","StatusCode":"A","Balance":126.24,"WithdrawableBalance":126.24,"AvailableBettingBalance":126.24,"AvailableRGBettingBalance":-1,"MaximumDepositableAmount":-1,"AccountStatusReasonID":0,"AccountType":{"AccountTypeID":1,"AccountType":"Primary Betting Account"}},{"ClientID":0,"AccountTypeID":2,"CurrencyCode":"AUD","StatusCode":"A","Balance":0,"WithdrawableBalance":0,"AvailableBettingBalance":0,"AvailableRGBettingBalance":-1,"MaximumDepositableAmount":0,"AccountStatusReasonID":0,"AccountType":{"AccountTypeID":2,"AccountType":"Bonus Account"}}],"ACTransactions":[],"Bets":[],"FreeBets":[{"FreeBetID":13506906,"PromotionID":16611,"FreeBetCriteriaID":3,"ClientID":0,"IssuedDate":"2019-03-11T23:31:57.903Z","ExpiryDate":"2019-09-11T23:31:57.903Z","FreeBetAmount":1,"WinningTurnoverFactor":1,"Notes":"","SplitGroupID":1,"FreeBetCriteria":{"FreeBetCriteriaID":3},"Promotion":{"PromotionID":16611,"PromoDescription":"My Rewards Welcome Bonus","IsActive":false,"PromoStartDate":"2019-02-27T04:43:24.157Z","PromoEndDate":"2019-03-27T12:59:59.157Z","IsRestrictedToClientList":false,"IsRestrictedToReferredClient":false}}],"RClientAccountRules":[{"ClientID":2964429,"AccountRuleID":152,"LAccountRule":{"AccountRuleID":152,"AccountRule":"No Points Redemption","RuleType":"R"}}],"ClientEmailVerifications":[],"ClientMobileVerifications":[],"PendingBets":[],"isBoostEligible":false}],"success":true}
            });
        cy.visit('https://beteasy.com.au/');
        cy.get('.TopBarDropDown__login--2uNhd').click();
        cy.get('input[class="Field__fieldInput--eWNRA"][type="text"]').type('abc@abc.com');
        cy.get('input[class="Field__fieldInput--eWNRA"][type="password"]').type('pwd{enter}');
    });
});